/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

//import com.microsoft.sqlserver.jdbc.SQLServerException;
import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Conexion;

/**
 *
 * @author Dachapi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Login");
        setIconImage (new ImageIcon(getClass().getResource("/complementos/icono.png")).getImage());
    }

    
    void Logearse(){
        int existe = 0;
        
       try {

            Statement st = Conexion.getConexion().createStatement();

            String consulta = "select count (*)from usuarios "
                    + "where Codigo_Usuarios = " + txtIdUsuario.getText() + " and "
                    + "Usuario = '" + txtUsuario.getText() + "' and "
                    + "Contrasenna = " + txtPassword.getText() + " ";

            ResultSet rs = st.executeQuery(consulta);

            while (rs.next()) {
                existe = rs.getInt(1);
            }
            if (Integer.parseInt(CboxEdad.getSelectedItem().toString()) >= 18) {
                if (existe == 1) {
                    new ventanaPrincipal(Integer.parseInt(txtIdUsuario.getText())).setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "¡Datos incorrectos! \n Recomendación: \n Ingrese un usuario registrado con anterioridad");
                }
            } else {
                JOptionPane.showMessageDialog(null, "¡Alerta! \n Edad: \n Usuario menor de edad Acceso denegado");
                this.dispose();
            }
        } catch (SQLServerException ex) {
            Logger.getLogger(cartaObtenida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(cartaObtenida.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    
    void revisar(){
        int id = 0;
        
        try {
            id = Integer.parseInt(txtIdUsuario.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "¡Alerta! \n Datos incorrectos: \n en el campo del id digite un numero registrado \n Ejemplo: 1,2,3,4...");
            this.dispose();
            new Login().setVisible(true);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblidUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        CboxEdad = new javax.swing.JComboBox<>();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblidUsuario.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        lblidUsuario.setText("Id Usuario :");
        jPanel1.add(lblidUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 30));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        lblUsuario.setText("Usuario : ");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 30));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        lblPassword.setText("Password : ");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 80, 30));

        lblEdad.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        lblEdad.setText("Edad : ");
        jPanel1.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 30));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 90, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, -1));
        jPanel1.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 90, -1));

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 160, -1));

        CboxEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50" }));
        CboxEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxEdadActionPerformed(evt);
            }
        });
        jPanel1.add(CboxEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/FondoLogin.jpeg"))); // NOI18N
        jPanel1.add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        revisar();
        Logearse();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void CboxEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxEdad;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblidUsuario;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
